// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	image: {
		repository: "ghcr.io/vatsalpatel/podinfo"
		tag:        "1.0.0"
		digest:     ""
	}
	test: image: {
		repository: "ghcr.io/curl/curl-container/curl-multi"
		tag:        "master"
		digest:     ""
	}
}
